services:
  - type: web
    name: tpgp-generator
    runtime: python
    plan: free
    rootDir: tpgp-generator
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 --timeout 120 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
